version: "3"
services:
  mysql:
    image: mysql:5.7.28
    container_name: mysql
    ports:
      - "3306:3306"
    volumes:
      - ./conf/mysql.cnf:/etc/mysql/conf.d/mysql.cnf:ro
      - ./data/mysql:/var/lib/mysql/:rw
    restart: always
    networks:
      - default
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
      TZ: "Asia/Shanghai"

  canal:
    depends_on:
      - mysql
    image: canal/canal-server
    deploy:
      resources:
        limits:
          memory: 4096M
    container_name: canal-server
    ports:
      - "11110:11110"
      - "11111:11111"
      - "11112:11112"
      - "9100:9100"
    volumes:
      - ./canalLogs:/home/admin/canal-server/logs:rw
    restart: always
    networks:
      - default
    environment:
      canal.instance.master.address: "mysql:3306"
      canal.instance.dbUsername: "canal"
      canal.instance.dbPassword: "canal"
      canal.instance.connectionCharset: "UTF-8"
      canal.instance.tsdb.enable: "true"
      canal.instance.gtidon: "false" 

networks:
  default:
