version: '2.2'
services:
  es:
    build:
      context: ./elasticsearch
    container_name: es
    environment:
      - node.name=es
      - cluster.name=es-docker-cluster
      - discovery.type=single-node
      - TZ="Asia/Shanghai"
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./elasticsearch/data/es01:/usr/share/elasticsearch/data
      - ./elasticsearch/logs/es01:/usr/share/elasticsearch/logs
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./elasticsearch/config/elastic-certificates.p12:/usr/share/elasticsearch/config/elastic-certificates.p12
    ports:
      - 9200:9200
    restart: always
    networks:
      - elastic

  kibana:
    depends_on:
      - es
    image: kibana:7.1.1
    container_name: kibana
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_URL: http://es:9200
      TZ: "Asia/Shanghai"
    volumes:
      - ./kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml
    restart: always
    networks:
      - elastic

networks:
  elastic:
    driver: bridge